### ISSUE TITLE
Spotify?

### ISSUE THREAD

**Issue by TechnicallyJoe** [meilon/DenonCMD#3]
Hello there, I'm trying to figure out the api to the Denon AVR, and DenonCMD works as intended. However i'd like to control the spotify app on the denon AVR x200 (which does not support spotify connect)

Do you have any idea how one would go about doing this?

PS: Couldn't figure out a way to write directly to you :)

**Comment by meilon** [comment]
Hi!
Like the Readme says, I build it to easily control my Denon from a Rainmeter skin. Getting into the Spotify menu, selecting a playlist and starting it is to complicated when you don't see the screen, so I used either the iOS app, the regular IR remote or the webapp. Once its playing a track I use just the volume and playback controls of my app.
It wouldn't be to hard to get the API to control all aspects of the Spotify portion, but I'd rather use it the mentioned way

**Comment by TechnicallyJoe** [comment]
By API you mean the official documented RS232 API right?
I've tried using it to no avail, using Telnet to communicate with it.

On a different note the http API seems to be lacking documentation, big time. Best I've found is http://blue-pc.net/2013/12/28/denon-av-reciever-ueber-http-steuern/ which is in a language, i don't understand. 

I'd like to figure out a way to control the spotify menu, without having to see the screen. I.e get some sort of feedback -> Open Spotify playlists and get a list of options, for example, choose one, and get a list of tracks in that playlist, stuff like that.
OR
At the very least, be able to navigate the UI and get feedback as to what the UI is currently seeing. without having to turn on my UI that is :P

I know it's possible to some degree because I've seen a few remote control apps be able to do it. But the UI's are always horrific, and I'd like to remedy that. :P

**Comment by meilon** [comment]
No, I meant the HTTP API. I got all my commands by using the web app in Chrome with the network tab open in the developer console. If you are developing your own app, using either developer console or wireshark is what you need and simply try sending the same commands the web interface does. A harder Setup would be the use a proxy and use the app on your smartphone, I would only go that way if I couldn't reproduce a working command from the web interface

**Comment by TechnicallyJoe** [comment]
I just checked the developer console on Chrome and it seems the way the Web interface navigates is just using something like this: 

cmd0:PutNetAudioCommand/CurDown
cmd1:osThreadSleep/50
cmd2:PutNetAudioCommand/CurDown
cmd3:osThreadSleep/50
cmd4:PutNetAudioCommand/CurDown
cmd5:osThreadSleep/50
cmd6:PutNetAudioCommand/CurRight

Basically, it just goes down one. waits, down one, waits. down one, waits and then goes right.
... Interesting approach they've taken ;p

I can't help but wonder if the original API RS323 can do this better, or if this is just how it's controlled.

**Comment by meilon** [comment]
When I click on the Spotify Icon on the webinterface, I get just these two commands where only the first and last command should be relevant: 

```
cmd0:PutZone_InputFunction/SPOTIFY
cmd1:aspMainZone_WebUpdateStatus/
ZoneName:MAIN ZONE
```

**Comment by TechnicallyJoe** [comment]
Yeah. the problem then becomes, how do you present the playlists n stuff,
in a proper maner? Or, choose it in a proper way, that doesnt involve
manually executing X down commands, followed by a right/left command.

If you choose spotify and then playlists n stuff,  theb youll see what i
meant in my previous post.

**Comment by meilon** [comment]
DenonCMD is meant to be silent, to not return anything. If you need that than perhaps you need to write your own app.
