### ISSUE TITLE
Compiling the new version

### ISSUE THREAD

**Issue by visormail** [meilon/DenonCMD#5]
Hello

I used this command:
C:\Windows\Microsoft.NET\Framework\v4.0.30319\csc.exe /t:exe /out:DenonCMD.exe Program.cs

Im getting this message:
Program.cs(185,24): error CS0246: The type or namespace name 'PostParam' could not be found (are you missing a using directive or an assembly reference?)
Program.cs(204,24): error CS0246: The type or namespace name 'PostParam' could not be found (are you missing a using directive or an assembly reference?)

**Comment by meilon** [comment]
I use Visual Studio to build, but with `msbuild` you should get the same result:

    c:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe /property:Configuration=Release DenonCMD.csproj

If you really want to use csc directly, you have to add all the code files manually:

    C:\Windows\Microsoft.NET\Framework\v4.0.30319\csc.exe /t:exe /out:DenonCMD.exe Program.cs HttpPost.cs
